# @format

version: "3"
services:
  cybergangs:
    container_name: user-manual-kiosko
    hostname: user-manual-kiosko
    # image: cybergangs
    build: ./
    restart: always
    ports:
      - 8080:8080
    #volumes:
    #  - "./front:/usr/share/nginx/html"
    # networks:
    #   - proxy_red_principal
    environment:
      VIRTUAL_HOST: localhost:8080
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: localhost:8080
      PUBLIC_URL: "http://localhost:8080"
# networks:
#   proxy_red_principal:
#     external: true